//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacione
    {
        public int CotizacionID { get; set; }
        public int ClienteID { get; set; }
        public System.DateTime Fecha { get; set; }
        public int UserID { get; set; }
        public bool Facturada { get; set; }
        public Nullable<decimal> DescuentoCliente { get; set; }
    }
}
