//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCotizacione
    {
        public int DetalleCotizacionID { get; set; }
        public int CotizacionID { get; set; }
        public int ProductoID { get; set; }
        public double Cantidad { get; set; }
        public decimal Precio { get; set; }
        public decimal ITBIS { get; set; }
        public decimal Descuento { get; set; }
    }
}
