//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleOrdenesCompra
    {
        public int DetalleOrdenCompraID { get; set; }
        public int OrdenCompraID { get; set; }
        public int ProductoID { get; set; }
        public double CantidadOrdenada { get; set; }
        public Nullable<double> CantidadRecibida { get; set; }
        public decimal Precio { get; set; }
        public bool Estatus { get; set; }
    
        public virtual OrdenesCompra OrdenesCompra { get; set; }
    }
}
