//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineasCreditoCompra
    {
        public int LineaCreditoCompraID { get; set; }
        public bool Estatus { get; set; }
        public int FacturaCompraID { get; set; }
    }
}
