//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagosComprasCredito
    {
        public int PagoCompraCreditoID { get; set; }
        public int LineaCompraCreditoID { get; set; }
        public System.DateTime FechaPago { get; set; }
        public decimal Monto { get; set; }
        public int UserID { get; set; }
        public string Concepto { get; set; }
    }
}
